version: '3.7'

services:
  psql:
    image: postgres:15
    container_name: 'psql'
    ports:
      - "${POSTGRES_PORT-5432}:${POSTGRES_PORT-5432}"
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=psql
  storefront:
    build:
      context: ./storefront
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "${STOREFRONT_PORT-8000}:${STOREFRONT_PORT-8000}"
    depends_on:
      psql:
        condition: service_started
    environment:
      POSTGRES_URL: ${WAZON_DB_URL}
      PORT: ${PORT-8000}
    env_file:
      - .env
  delivery:
    build:
      context: ./delivery
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "${DELIVERY_PORT-8001}:${DELIVERY_PORT-8001}"
    depends_on:
      psql:
        condition: service_started
    environment:
      POSTGRES_URL: ${WAZON_DB_URL}
      PORT: ${PORT-8001}
    env_file:
      - .env