version: '3.7'

services:
  psql:
    image: postgres:15
    container_name: 'psql'
    ports:
      - '5432:5432' # For debug, drop in prod
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=psql
  storefront:
    build:
      context: ./storefront
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - '8000:8000'
    depends_on:
      psql:
        condition: service_started
    environment:
      POSTGRES_URL: ${WAZON_DB_URL}
    env_file:
      - .env
  delivery:
    build:
      context: ./delivery
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - '8001:8001'
    depends_on:
      psql:
        condition: service_started
    environment:
      POSTGRES_URL: ${WAZON_DB_URL}
    env_file:
      - .env