version: '3.7'

services:
  psql:
    image: postgres:15
    container_name: 'psql'
    ports:
      - "${POSTGRES_PORT-5432}:${POSTGRES_PORT-5432}"
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=psql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
  rabbitmq:
    image: rabbitmq:3.13.1-management
    hostname: rabbitmq
    restart: on-failure
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 5s
      timeout: 5s
      retries: 5
  storefront:
    build:
      context: ./storefront
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "${STOREFRONT_PORT-8000}:${STOREFRONT_PORT-8000}"
    depends_on:
      psql:
        condition: service_healthy
    environment:
      POSTGRES_URL: ${WAZON_DB_URL}
      PORT: ${PORT-8000}
    env_file:
      - .env
  delivery:
    build:
      context: ./delivery
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "${DELIVERY_PORT-8001}:${DELIVERY_PORT-8001}"
    depends_on:
      psql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      POSTGRES_URL: ${WAZON_DB_URL}
      PORT: ${PORT-8001}
    env_file:
      - .env
  account:
    build:
      context: ./accountService
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "${ACCOUNT_PORT-8002}:${ACCOUNT_PORT-8002}"
    depends_on:
      psql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      POSTGRES_URL: ${WAZON_DB_URL}
      PORT: ${PORT-8002}
    env_file:
      - .env