name: golangci-lint-all-dirs-with-gomod
on:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.57.1
      - name: Find Go modules and run golangci-lint
        run: |
          for dir in $(find . -name 'go.mod' -exec dirname {} \;); do
            echo "Running golangci-lint in $dir"
            golangci-lint run --config ./.github/golangci.yml --path $dir
          done