name: golangci-lint-all-dirs-with-gomod
on:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.57.1
      - name: Generate config
        run: bash .github/scripts/generate-lint-config.sh
      - name: Run golangci-lint
        run: |
          for dir in $(find . -name "go.mod" -exec dirname {} \; | sort -u | xargs -I {} realpath {}); do
            cd $dir && golangci-lint run --fix
          done